/* Warm-up chains — the Module 2 mechanisms, one bead blanked before a mini paper.
   These are the tool's own scaffolds built FROM her decks (each names its source);
   they are not her material and the ? sheet says so. Bead wording follows the
   course's own vocabulary (e.g. her AP quiz's "depolarisation … Na+ moves IN"). */
export const CHAINS = [
  {
    id: 'fracture-healing', sys: 'ms', name: 'Healing of a bone fracture',
    src: '2026 MS1 deck · "Bone fractures, cells & repair" page',
    beads: [
      { t: 'Fracture — vessels in bone and periosteum tear' },
      { v: 'blood pools and clots as a' },
      { t: 'Haematoma' },
      { v: 'fibroblasts + chondrocytes bridge the break as a' },
      { t: 'Fibrocartilaginous (soft) callus' },
      { v: 'osteoblasts replace it with spongy bone — the' },
      { t: 'Bony (hard) callus' },
      { v: 'is reshaped along stress lines by' },
      { t: 'Bone remodelling (osteoclasts + osteoblasts)' },
    ],
  },
  {
    id: 'calcium', sys: 'ms', name: 'Low blood calcium — the PTH response',
    src: '2026 MS1 + Endocrine 2 decks (criterion: PTH · calcitonin · calcitriol)',
    beads: [
      { t: 'Blood Ca²⁺ falls' },
      { v: 'detected by the' },
      { t: 'Parathyroid glands' },
      { v: 'which secrete' },
      { t: 'PTH' },
      { v: 'stimulating osteoclasts to' },
      { t: 'Resorb bone matrix, releasing Ca²⁺' },
      { v: 'while the kidneys reabsorb Ca²⁺ and activate' },
      { t: 'Calcitriol → more Ca²⁺ absorbed from the gut' },
      { v: 'so' },
      { t: 'Blood Ca²⁺ rises back to the set point' },
    ],
  },
  {
    id: 'action-potential', sys: 'ns', name: 'The action potential',
    src: '2026 NS1 deck · her "Neuron, AP & Synapse" quiz',
    beads: [
      { t: 'Resting membrane potential (−70 mV, Na⁺/K⁺ pump)' },
      { v: 'a stimulus reaches threshold, so' },
      { t: 'Voltage-gated Na⁺ channels open — Na⁺ moves IN' },
      { v: 'the inside becomes positive:' },
      { t: 'Depolarisation' },
      { v: 'Na⁺ gates close, K⁺ channels open — K⁺ moves OUT:' },
      { t: 'Repolarisation' },
      { v: 'K⁺ overshoots briefly:' },
      { t: 'Hyperpolarisation, then the pump restores rest' },
      { v: 'the wave self-propagates — myelinated axons jump node to node:' },
      { t: 'Saltatory conduction (faster in thick, myelinated fibres)' },
    ],
  },
  {
    id: 'synapse', sys: 'ns', name: 'Synaptic transmission',
    src: '2026 NS1 deck (criterion ns-9: "in detail")',
    beads: [
      { t: 'Action potential arrives at the axon terminal' },
      { v: 'voltage-gated channels open and' },
      { t: 'Ca²⁺ flows into the terminal' },
      { v: 'triggering synaptic vesicles to fuse and release' },
      { t: 'Neurotransmitter into the synaptic cleft' },
      { v: 'it diffuses across and binds' },
      { t: 'Receptors on the postsynaptic membrane' },
      { v: 'ion channels open and the impulse continues, until the transmitter is' },
      { t: 'Broken down or taken back up (signal ends)' },
    ],
  },
  {
    id: 'reflex-arc', sys: 'ns', name: 'The reflex arc',
    src: '"Spinal Nerves and the Reflex Arc" page · 2026 NS3',
    beads: [
      { t: 'Receptor detects the stimulus' },
      { v: 'impulse travels along the' },
      { t: 'Sensory (afferent) neuron' },
      { v: 'into the' },
      { t: 'Integration centre in the spinal cord' },
      { v: 'out along the' },
      { t: 'Motor (efferent) neuron' },
      { v: 'to the' },
      { t: 'Effector (muscle or gland) — the response' },
    ],
  },
  {
    id: 'blood-glucose', sys: 'endo', name: 'Blood glucose regulation',
    src: 'Endocrine 2 deck · her "Regulating Blood Sugar" quiz',
    beads: [
      { t: 'Blood glucose rises after a meal' },
      { v: 'beta cells of the pancreatic islets release' },
      { t: 'Insulin' },
      { v: 'muscle + adipose take glucose up, the liver stores it as glycogen, so' },
      { t: 'Blood glucose falls to the set point' },
      { v: 'if it falls too far, alpha cells release' },
      { t: 'Glucagon' },
      { v: 'the liver breaks glycogen down (glycogenolysis) and makes new glucose, so' },
      { t: 'Blood glucose rises — negative feedback both ways' },
    ],
  },
  {
    id: 'thyroid-axis', sys: 'endo', name: 'Hypothalamus → pituitary → thyroid',
    src: 'Endocrine 1 deck (control of hormone secretion · feedback cycles)',
    beads: [
      { t: 'Hypothalamus releases TRH' },
      { v: 'which tells the' },
      { t: 'Anterior pituitary to release TSH' },
      { v: 'which stimulates the' },
      { t: 'Thyroid to release T3 / T4' },
      { v: 'raising metabolic rate — and high T3/T4' },
      { t: 'Feed back to SUPPRESS TRH and TSH (negative feedback)' },
    ],
  },
];
