/* Warm-up chains — the Module 2 mechanisms, one bead blanked before a mini paper.
   These are the tool's own scaffolds built FROM her decks (each names its source);
   they are not her material and the ? sheet says so. Bead wording follows the
   course's own vocabulary (e.g. her AP quiz's "depolarisation … Na+ moves IN"). */
export const CHAINS = [
  {
    id: 'fracture-healing', sys: 'ms', name: 'Healing of a bone fracture',
    src: '2026 MS1 deck · "Bone fractures, cells & repair" page',
    beads: [
      { t: 'Fracture — vessels in bone and periosteum tear' },
      { v: 'blood pools and clots as a' },
      { t: 'Haematoma' },
      { v: 'fibroblasts + chondrocytes bridge the break as a' },
      { t: 'Fibrocartilaginous (soft) callus' },
      { v: 'osteoblasts replace it with spongy bone — the' },
      { t: 'Bony (hard) callus' },
      { v: 'is reshaped along stress lines by' },
      { t: 'Bone remodelling (osteoclasts + osteoblasts)' },
    ],
  },
  {
    id: 'calcium', sys: 'ms', name: 'Low blood calcium — the PTH response',
    src: '2026 MS1 + Endocrine 2 decks (criterion: PTH · calcitonin · calcitriol)',
    beads: [
      { t: 'Blood Ca²⁺ falls' },
      { v: 'detected by the' },
      { t: 'Parathyroid glands' },
      { v: 'which secrete' },
      { t: 'PTH' },
      { v: 'stimulating osteoclasts to' },
      { t: 'Resorb bone matrix, releasing Ca²⁺' },
      { v: 'while the kidneys reabsorb Ca²⁺ and activate' },
      { t: 'Calcitriol → more Ca²⁺ absorbed from the gut' },
      { v: 'so' },
      { t: 'Blood Ca²⁺ rises back to the set point' },
    ],
  },
  {
    id: 'action-potential', sys: 'ns', name: 'The action potential',
    src: '2026 NS1 deck · her "Neuron, AP & Synapse" quiz',
    beads: [
      { t: 'Resting membrane potential (−70 mV, Na⁺/K⁺ pump)' },
      { v: 'a stimulus reaches threshold, so' },
      { t: 'Voltage-gated Na⁺ channels open — Na⁺ moves IN' },
      { v: 'the inside becomes positive:' },
      { t: 'Depolarisation' },
      { v: 'Na⁺ gates close, K⁺ channels open — K⁺ moves OUT:' },
      { t: 'Repolarisation' },
      { v: 'K⁺ overshoots briefly:' },
      { t: 'Hyperpolarisation, then the pump restores rest' },
      { v: 'the wave self-propagates — myelinated axons jump node to node:' },
      { t: 'Saltatory conduction (faster in thick, myelinated fibres)' },
    ],
  },
  {
    id: 'synapse', sys: 'ns', name: 'Synaptic transmission',
    src: '2026 NS1 deck (criterion ns-9: "in detail")',
    beads: [
      { t: 'Action potential arrives at the axon terminal' },
      { v: 'voltage-gated channels open and' },
      { t: 'Ca²⁺ flows into the terminal' },
      { v: 'triggering synaptic vesicles to fuse and release' },
      { t: 'Neurotransmitter into the synaptic cleft' },
      { v: 'it diffuses across and binds' },
      { t: 'Receptors on the postsynaptic membrane' },
      { v: 'ion channels open and the impulse continues, until the transmitter is' },
      { t: 'Broken down or taken back up (signal ends)' },
    ],
  },
  {
    id: 'reflex-arc', sys: 'ns', name: 'The reflex arc',
    src: '"Spinal Nerves and the Reflex Arc" page · 2026 NS3',
    beads: [
      { t: 'Receptor detects the stimulus' },
      { v: 'impulse travels along the' },
      { t: 'Sensory (afferent) neuron' },
      { v: 'into the' },
      { t: 'Integration centre in the spinal cord' },
      { v: 'out along the' },
      { t: 'Motor (efferent) neuron' },
      { v: 'to the' },
      { t: 'Effector (muscle or gland) — the response' },
    ],
  },
  {
    id: 'blood-glucose', sys: 'endo', name: 'Blood glucose regulation',
    src: 'Endocrine 2 deck · her "Regulating Blood Sugar" quiz',
    beads: [
      { t: 'Blood glucose rises after a meal' },
      { v: 'beta cells of the pancreatic islets release' },
      { t: 'Insulin' },
      { v: 'muscle + adipose take glucose up, the liver stores it as glycogen, so' },
      { t: 'Blood glucose falls to the set point' },
      { v: 'if it falls too far, alpha cells release' },
      { t: 'Glucagon' },
      { v: 'the liver breaks glycogen down (glycogenolysis) and makes new glucose, so' },
      { t: 'Blood glucose rises — negative feedback both ways' },
    ],
  },
  /* The four below are named OUTRIGHT in her "Diagrams & Processes in Test 2"
     post (discussion 413313) as sequential processes Test 2 may examine. */
  {
    id: 'csf', sys: 'ns', name: 'Cerebrospinal fluid — production to reabsorption',
    src: 'Her Test-2 focus post · 2026 NS2 deck (protection of the CNS)',
    beads: [
      { t: 'Choroid plexuses in the ventricles produce CSF' },
      { v: 'it flows through the' },
      { t: 'Lateral ventricles → third ventricle → cerebral aqueduct → fourth ventricle' },
      { v: 'then out into the' },
      { t: 'Subarachnoid space, bathing brain and spinal cord' },
      { v: 'and is finally reabsorbed into venous blood through the' },
      { t: 'Arachnoid villi (granulations) into the dural sinuses' },
    ],
  },
  {
    id: 'endochondral', sys: 'ms', name: 'Endochondral ossification (long bones)',
    src: 'Her Test-2 focus post · 2026 MS1 deck',
    beads: [
      { t: 'Hyaline cartilage template of the future bone' },
      { v: 'a bone collar forms and the centre calcifies, then' },
      { t: 'Blood vessels invade — the primary ossification centre' },
      { v: 'osteoblasts replace cartilage with bone toward the ends, and after birth' },
      { t: 'Secondary ossification centres form in the epiphyses' },
      { v: 'leaving cartilage only at the' },
      { t: 'Epiphyseal (growth) plates and articular surfaces' },
      { v: 'growth ends when the plates close — the' },
      { t: 'Epiphyseal line' },
    ],
  },
  {
    id: 'intramembranous', sys: 'ms', name: 'Intramembranous ossification (flat bones)',
    src: 'Her Test-2 focus post · 2026 MS1 deck (skull, clavicle, sternum)',
    beads: [
      { t: 'A sheet of mesenchymal (fibrous) tissue — no cartilage template' },
      { v: 'cells cluster and differentiate into' },
      { t: 'Osteoblasts at an ossification centre' },
      { v: 'which secrete osteoid that calcifies into' },
      { t: 'Trabeculae of spongy bone' },
      { v: 'compact bone plates form at the surfaces, giving the' },
      { t: 'Flat bones — skull, clavicle, sternum' },
    ],
  },
  {
    id: 'hpa-axis', sys: 'endo', name: 'Hypothalamus → pituitary → adrenal cortex',
    src: 'Her Test-2 focus post · Endocrine 1–2 decks (stress cascade)',
    beads: [
      { t: 'Stress — the hypothalamus releases CRH' },
      { v: 'which tells the' },
      { t: 'Anterior pituitary to release ACTH' },
      { v: 'which stimulates the' },
      { t: 'Adrenal CORTEX to release cortisol' },
      { v: 'raising blood glucose and suppressing inflammation — and high cortisol' },
      { t: 'Feeds back to SUPPRESS CRH and ACTH (negative feedback)' },
    ],
  },
  {
    id: 'thyroid-axis', sys: 'endo', name: 'Hypothalamus → pituitary → thyroid',
    src: 'Endocrine 1 deck (control of hormone secretion · feedback cycles)',
    beads: [
      { t: 'Hypothalamus releases TRH' },
      { v: 'which tells the' },
      { t: 'Anterior pituitary to release TSH' },
      { v: 'which stimulates the' },
      { t: 'Thyroid to release T3 / T4' },
      { v: 'raising metabolic rate — and high T3/T4' },
      { t: 'Feed back to SUPPRESS TRH and TSH (negative feedback)' },
    ],
  },
];
